version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    assignees:
      - MartsTech
    ignore:
      - dependency-name: "firebase"
      - dependency-name: "react-native-safe-area-context"
      - dependency-name: "react-native-screens"
